#!/usr/bin/python

"""
Author             : Mary
contact            : mary.developer@gmail.com
Github             : https://github.com/Mary
my youtube channel : Mary

STOP HACKING!!!
"""

import sys
import os.path
import subprocess

The author is not responsible for your actions, Maxi-Tool is made only for the author
Maxi-Tool author make this tool for him! Autor Maxi-Tool don't tell you do something with this tool!!
Author name: Mary
Author ip: 79.23.104.57

#STOP HACKING!
;

```
1.if installed is complite, use command
$cd
2.then run it
$Maxi-Tool
```

**NOTE:**
```
if python2 install.py is not allowed or fail, Use this
$chmod +x install.py
$python2 install.py
```
**how to update:**

for update this tool, just do the reinstallation, the first way is to install the Darkfly tools, by reinstalling, the old file will be deleted and replaced with the new one installed.
# note
```
the DarkFly tools on linux does not working
```

# support me
<a href="https://www.youtube.com/channel/UCNMD5U02GFeWLqmrl_XSPGQ"><img src="https://img.shields.io/badge/subcribe-YouTube-red.svg">
#Discalimer
 Maxi-Tool autor make this tool for him! Autor Maxi-Tool don't tell you do something with this tool!!

Maxi-Tool author make this tool for him! Autor Maxi-Tool don't tell you do something with this tool!!
Author name: Mary
Author ip: 79.23.104.57

The author is not responsible for your actions, Maxi-Tool is made only for the authoinstall:

**Termux:**

* `pkg install python2`
* `pkg install git`
* `git clone https://github.com/Ranginang67/Maxi-Tool`
* `cd Maxi-Tool`
* `python2 install.py`

```
1.if installed is complite, use command
$cd
2.then run it
$Maxi-Tool
```

**NOTE:**
```
if python2 install.py is not allowed or fail, Use this
$chmod +x install.py
$python2 install.py
```
**how to update:**

for update this tool, just do the reinstallation, the first way is to install the Darkfly tools, by reinstalling, the old file will be deleted and replaced with the new one installed.
# note
```
the DarkFly tools on linux does not working
```

# support me
<a href="https://www.youtube.com/channel/UCNMD5U02GFeWLqmrl_XSPGQ"><img src="https://img.shields.io/badge/subcribe-YouTube-red.svg">
#Discalimer
 Maxi-Tool autor make this tool for him! Autor Maxi-Tool don't tell you do something with this tool!!

Maxi-Tool author make this tool for him! Autor Maxi-Tool don't tell you do something with this tool!!
Author name: Mary
Author ip: 79.23.104.57

The author is not responsible for your actions, Maxi-Tool is made only for the autinstall:

**Termux:**

* `pkg install python2`
* `pkg install git`
* `git clone https://github.com/Ranginang67/Maxi-Tool`
* `cd Maxi-Tool`
* `python2 install.py`

```
1.if installed is complite, use command
$cd
2.then run it
$Maxi-Tool
```

**NOTE:**
```
if python2 install.py is not allowed or fail, Use this
$chmod +x install.py
$python2 install.py
```
**how to update:**

for update this tool, just do the reinstallation, the first way is to install the Darkfly tools, by reinstalling, the old file will be deleted and replaced with the new one installed.
# note
```
the DarkFly tools on linux does not working
```

#Discalimer
 Maxi-Tool autor make this tool for him! Autor Maxi-Tool don't tell you do something with this tool!!

Maxi-Tool author make this tool for him! Autor Maxi-Tool don't tell you do something with this tool!!
Author name: Mary
Author ip: 79.23.104.57

The author is not responsible for your actions, Maxi-Tool is made only for the a
#Discalimer
 Maxi-Tool autor make this tool for him! Autor Maxi-Tool don't tell you do something with this tool!!

Maxi-Tool author make this tool for him! Autor Maxi-Tool don't tell you do something with this tool!!
Author name: Mary
Author ip: 79.23.104.57

The author is not responsible for your actions, Maxi-Tool is made only for the author!

#STOP HACKING!!!